"""
exercise_pdf package — re-exports everything for backwards compatibility.

All public names remain importable from src.bible_grammar.exercise_pdf as before.
"""
from ._base import (
    ExercisePDF,
    PassageExercise,
    VerbEntry,
    PassageBlock,
    ContrastEntry,
    NHEntry,
    BGEntry,
    SortEntry,
    _build_exercise_pdf,
    _register_fonts,
    _heb,
    C_HEADER_BG, C_ANSWER_BG, C_ANSWER_FG, C_WATCHOUT, C_WATCHOUT_B,
    C_FIELD_BG, C_RULE, C_HEADING, C_REF, C_NOTE_BG, C_NOTE_B,
    C_SCORE_BG, C_SCORE_B,
    UNICODE_TRANSLIT_FONT,
)
from ._greek import GreekExercisePDF
from .bbh import (
    # Ch24–Ch35 BBH exercise classes
    Ch26Exercise,
    Ch26ContrastExercise,
    Ch26FunctionSortExercise,
    Ch25Exercise,
    Ch24Exercise,
    Ch24ContrastExercise,
    Ch24FunctionSortExercise,
    Ch25WeakFormIdExercise,
    Ch27Exercise,
    Ch27WeakFormIdExercise,
    Ch27NHContrastExercise,
    Ch27BGDrillExercise,
    Ch30PielExercise,
    Ch28HophalExercise,
    Ch34HithpaelExercise,
    Ch35HithpaelWeakExercise,
    Ch29HophalWeakExercise,
    Ch31PielWeakExercise,
    Ch32PualExercise,
    Ch33PualWeakExercise,
    # Ch1–Ch23 BBH exercise classes
    Ch1LetterRecognitionExercise,
    Ch2VowelIdentificationExercise,
    Ch3SyllableDivisionExercise,
    Ch4NounParsingExercise,
    Ch5ArticleAndVavExercise,
    Ch6PrepositionParsingExercise,
    Ch7AdjectiveUsageExercise,
    Ch8PronounIdentificationExercise,
    Ch9SuffixParsingExercise,
    Ch10ConstructChainExercise,
    Ch11NumberIdentificationExercise,
    Ch12VerbOverviewExercise,
    Ch13ParsingDrillExercise,
    Ch13PassageExercise,
    Ch14PassageExercise,
    Ch14WeakFormIdExercise,
    Ch15ParsingDrillExercise,
    Ch15PassageExercise,
    Ch16PassageExercise,
    Ch16WeakFormIdExercise,
    Ch17ParsingDrillExercise,
    Ch17PassageExercise,
    Ch18ParsingDrillExercise,
    Ch18PassageExercise,
    Ch19ParsingDrillExercise,
    Ch19PassageExercise,
    Ch20ParsingDrillExercise,
    Ch20PassageExercise,
    Ch21ParsingDrillExercise,
    Ch21PassageExercise,
    Ch22ParsingDrillExercise,
    Ch22PassageExercise,
    Ch23ClauseAnalysisExercise,
    Ch23PassageExercise,
    # BBH builder functions
    build_ch26_contrast_exercise,
    build_ch26_function_sort_exercise,
    build_ch26_exercise,
    build_ch25_exercise,
    build_ch24_exercise,
    build_ch24_contrast_exercise,
    build_ch24_function_sort_exercise,
    build_ch25_weak_form_id_exercise,
    build_ch27_exercise,
    build_ch27_weak_form_id_exercise,
    build_ch27_nh_contrast_exercise,
    build_ch27_bg_drill_exercise,
    build_ch30_exercise,
    build_ch28_hophal_exercise,
    build_ch34_hithpael_exercise,
    build_ch35_hithpael_weak_exercise,
    build_ch29_hophal_weak_exercise,
    build_ch31_piel_weak_exercise,
    build_ch32_exercise,
    build_ch33_exercise,
    build_ch1_letter_recognition,
    build_ch2_vowel_identification,
    build_ch3_syllable_division,
    build_ch4_noun_parsing,
    build_ch5_article_and_vav,
    build_ch6_preposition_parsing,
    build_ch7_adjective_usage,
    build_ch8_pronoun_identification,
    build_ch9_suffix_parsing,
    build_ch10_construct_chain,
    build_ch11_number_identification,
    build_ch12_verb_overview,
    build_ch13_parsing_drill,
    build_ch13_passage_exercise,
    build_ch14_passage_exercise,
    build_ch14_weak_form_id,
    build_ch15_parsing_drill,
    build_ch15_passage_exercise,
    build_ch16_passage_exercise,
    build_ch16_weak_form_id,
    build_ch17_parsing_drill,
    build_ch17_passage_exercise,
    build_ch18_parsing_drill,
    build_ch18_passage_exercise,
    build_ch19_parsing_drill,
    build_ch19_passage_exercise,
    build_ch20_parsing_drill,
    build_ch20_passage_exercise,
    build_ch21_parsing_drill,
    build_ch21_passage_exercise,
    build_ch22_parsing_drill,
    build_ch22_passage_exercise,
    build_ch23_clause_analysis,
    build_ch23_passage_exercise,
)
from .bbg import (
    build_bbg_ch3_alphabet_drill,
    build_bbg_ch4_syllable_drill,
    build_bbg_ch6_nom_acc_parsing,
    build_bbg_ch7_gen_dat_parsing,
    build_bbg_ch8_preposition_parsing,
    build_bbg_ch9_adjective_parsing,
    build_bbg_ch10_third_decl_parsing,
    build_bbg_ch11_pronoun_parsing,
    build_bbg_ch12_autos_parsing,
    build_bbg_ch13_demonstrative_parsing,
    build_bbg_ch14_relative_parsing,
    build_bbg_ch16_present_active_parsing,
    build_bbg_ch17_contract_verb_parsing,
    build_bbg_ch18_middle_passive_parsing,
    build_bbg_ch19_future_parsing,
    build_bbg_ch20_stem_change_drill,
    build_bbg_ch21_imperfect_parsing,
    build_bbg_ch22_second_aorist_parsing,
    build_bbg_ch23_first_aorist_parsing,
    build_bbg_ch24_aorist_future_passive_parsing,
    build_bbg_ch25_perfect_parsing,
    build_bbg_ch27_present_participle_parsing,
    build_bbg_ch28_aorist_participle_parsing,
    build_bbg_ch29_adjectival_participle_parsing,
    build_bbg_ch30_perfect_participle_genabs,
    build_bbg_ch31_subjunctive_parsing,
    build_bbg_ch32_infinitive_parsing,
    build_bbg_ch33_imperative_parsing,
    build_bbg_ch34_didomi_parsing,
    build_bbg_ch35_conditionals_drill,
    build_bbg_ch36_mi_verbs_parsing,
)
from .bba import (
    build_bba_ch1_letter_recognition,
    build_bba_ch2_vowel_identification,
    build_bba_ch3_syllabification_drill,
    build_bba_ch4_noun_identification,
    build_bba_ch5_determined_state_drill,
    build_bba_ch6_construct_chain_drill,
    build_bba_ch7_preposition_drill,
    build_bba_ch8_suffix_drill,
    build_bba_ch9_pronoun_drill,
    build_bba_ch10_adjective_number_drill,
    build_bba_ch11_particle_drill,
    build_bba_ch12_verb_intro_drill,
    build_bba_ch13_peal_perfect_drill,
    build_bba_ch14_peal_imperfect_drill,
    build_bba_ch15_peal_imperative_drill,
    build_bba_ch16_peal_infinitive_drill,
    build_bba_ch17_peal_participle_drill,
    build_bba_ch18_passive_stems_drill,
    build_bba_ch19_pael_stem_drill,
    build_bba_ch20_hithpaal_drill,
    build_bba_ch21_haphel_stem_drill,
    build_bba_ch22_causative_passive_drill,
)

__all__ = [
    # Base
    'ExercisePDF', 'PassageExercise',
    'VerbEntry', 'PassageBlock', 'ContrastEntry', 'NHEntry', 'BGEntry', 'SortEntry',
    '_build_exercise_pdf', '_register_fonts', '_heb',
    'C_HEADER_BG', 'C_ANSWER_BG', 'C_ANSWER_FG', 'C_WATCHOUT', 'C_WATCHOUT_B',
    'C_FIELD_BG', 'C_RULE', 'C_HEADING', 'C_REF', 'C_NOTE_BG', 'C_NOTE_B',
    'C_SCORE_BG', 'C_SCORE_B', 'UNICODE_TRANSLIT_FONT',
    # Greek
    'GreekExercisePDF',
]
